import {expect,test} from "bun:test";
import * as fs from "node:fs/promises";
import * as os from "node:os";
import {join} from "node:path";
import {PresenceRuntime} from "../src/runtime.js";
import {resolvePresenceConfig} from "../src/config.js";
import {fakeSocket} from "./helpers/fake-socket.js";
const pause=(ms=30)=>new Promise(resolve=>setTimeout(resolve,ms));

function environment(dir:string,socket:string){return {HERDR_ENV:"1",HERDR_SOCKET_PATH:socket,HERDR_PANE_ID:"pane",PI_CODING_AGENT_DIR:join(dir,"missing")};}
function restore(saved:Record<string,string|undefined>){for(const [key,value] of Object.entries(saved)){if(value===undefined)delete process.env[key];else process.env[key]=value;}}

test("agent_start refreshes path-preferred refs and native blocked counters are root-gated",async()=>{const dir=await fs.mkdtemp(join(os.tmpdir(),"herdr-safe-"));const socket=join(dir,"socket");const lines:string[]=[];const server=await fakeSocket(socket,line=>{lines.push(line);return JSON.stringify({id:JSON.parse(line).id,result:{}});});const keys=["HERDR_ENV","HERDR_SOCKET_PATH","HERDR_PANE_ID","PI_CODING_AGENT_DIR"];const saved=Object.fromEntries(keys.map(key=>[key,process.env[key]]));try{Object.assign(process.env,environment(dir,socket));const pi={getAllTools(){return[]},events:{emit(){}}};const runtime=new PresenceRuntime(pi as never,{...resolvePresenceConfig(),finalClearMs:0});runtime.handleBlocked({active:true,label:"ignored before root"});await runtime.startSession({mode:"tui",sessionManager:{getSessionId:()=>"root",getSessionFile:()=>"/sessions/first.jsonl"}});runtime.handleAgentStart({sessionManager:{getSessionId:()=>"root",getSessionFile:()=>"/sessions/second.jsonl"}});runtime.handleBlocked({active:false});runtime.handleBlocked({active:true,label:"Approval required"});runtime.handleBlocked({active:true,label:"Second approval"});await pause(40);runtime.handleBlocked({active:false});runtime.handleBlocked({active:false});await pause(120);const requests=lines.map(line=>JSON.parse(line));expect(requests.filter(request=>request.method==="pane.report_agent_session").at(-1).params.agent_session_path).toBe("/sessions/second.jsonl");expect(requests.find(request=>request.method==="pane.report_agent"&&request.params.state==="working")?.params.agent_session_path).toBe("/sessions/second.jsonl");expect(requests.some(request=>request.method==="pane.report_agent"&&request.params.state==="blocked"&&request.params.message==="Pi needs attention")).toBe(true);expect(requests.filter(request=>request.method==="pane.report_agent").at(-1)?.params.state).toBe("working");await runtime.shutdownSession();}finally{restore(saved);await server.close();await fs.rm(dir,{recursive:true,force:true});}});

test("blocked transitions notify again after an unblock in the same turn",async()=>{const dir=await fs.mkdtemp(join(os.tmpdir(),"herdr-blocked-notify-"));const socket=join(dir,"socket");const lines:string[]=[];const server=await fakeSocket(socket,line=>{lines.push(line);return JSON.stringify({id:JSON.parse(line).id,result:{}});});const keys=["HERDR_ENV","HERDR_SOCKET_PATH","HERDR_PANE_ID","PI_CODING_AGENT_DIR"];const saved=Object.fromEntries(keys.map(key=>[key,process.env[key]]));try{Object.assign(process.env,environment(dir,socket));const runtime=new PresenceRuntime({getAllTools(){return[]},events:{emit(){}}} as never,{...resolvePresenceConfig(),notificationPolicy:"errors"});await runtime.startSession({mode:"tui",sessionManager:{getSessionId:()=>"root"}});runtime.handleAgentStart();runtime.handleBlocked({active:true,label:"ask-user"});await pause(120);runtime.handleBlocked({active:false});runtime.handleBlocked({active:true,label:"ask-user"});await pause(120);expect(lines.map(line=>JSON.parse(line)).filter(request=>request.method==="notification.show")).toHaveLength(2);await runtime.shutdownSession();}finally{restore(saved);await server.close();await fs.rm(dir,{recursive:true,force:true});}});

test("managed marker leaves runtime entirely inactive",async()=>{const dir=await fs.mkdtemp(join(os.tmpdir(),"herdr-managed-off-"));const socket=join(dir,"socket");const keys=["HERDR_ENV","HERDR_SOCKET_PATH","HERDR_PANE_ID","PI_CODING_AGENT_DIR"];const saved=Object.fromEntries(keys.map(key=>[key,process.env[key]]));try{await fs.mkdir(join(dir,"extensions"));await fs.writeFile(join(dir,"extensions","herdr-agent-state.ts"),"HERDR_INTEGRATION_ID=pi");Object.assign(process.env,{...environment(dir,socket),PI_CODING_AGENT_DIR:dir});const emitted:string[]=[];const runtime=new PresenceRuntime({getAllTools(){return[]},events:{emit(name:string){emitted.push(name)}}} as never,resolvePresenceConfig());await runtime.startSession({mode:"tui",sessionManager:{getSessionId:()=>"root",getSessionFile:()=>"/sessions/root.jsonl"}});runtime.handlePresenceUpdate({version:1,sessionId:"root",generation:1,sequence:1,source:{id:"x",label:"X",kind:"task"},state:"running",counts:{active:1,completed:0,failed:0}});runtime.handleBlocked({active:true,label:"ignored"});expect(emitted).toEqual([]);await runtime.shutdownSession();}finally{restore(saved);await fs.rm(dir,{recursive:true,force:true});}});

test("runtime delegates cleanup to the aggregate client teardown budget",async()=>{const config={...resolvePresenceConfig(),timeoutMs:321};const runtime=new PresenceRuntime({getAllTools(){return[]},events:{emit(){}}} as never,config);const calls:number[]=[];(runtime as unknown as {client:{teardown:(timeoutMs:number)=>Promise<void>}|null}).client={async teardown(timeoutMs){calls.push(timeoutMs);}};await runtime.shutdownSession();expect(calls).toEqual([321]);});
