import type { PresenceUpdate } from "./events.js";
/** Exact producer identity; labels/kinds never grant special routing authority. */
export const PI_SUBAGENT_SOURCE_ID = "pi-subagent";
export type NotificationPolicy = "errors" | "background" | "settled" | "all" | "disabled";
export type AttentionKind = "success" | "error";
export interface SubagentTerminalBaseline { readonly generation:number; readonly completed:number; readonly failed:number; readonly cancelled:number; }
export interface SubagentObservation { readonly baseline:SubagentTerminalBaseline; readonly terminal:AttentionKind|null; readonly completedDelta:number; readonly failedDelta:number; readonly reset:boolean; readonly generationChanged:boolean; readonly unknownCount:boolean; }
const baseline=(e:PresenceUpdate):SubagentTerminalBaseline=>({generation:e.generation,completed:e.counts.completed,failed:e.counts.failed,cancelled:e.counts.cancelled??0});
/** Interpret only pi-subagent's cumulative counters; cancellation has no attention. */
export function observeSubagentTerminal(previous:SubagentTerminalBaseline|null,event:PresenceUpdate):SubagentObservation {const next=baseline(event);const attention=event.state==="cancelled"?null:event.attention==="error"?"error":event.attention==="success"||event.attention==="info"?"success":null;if(event.source.id!==PI_SUBAGENT_SOURCE_ID)return{baseline:next,terminal:null,completedDelta:0,failedDelta:0,reset:false,generationChanged:false,unknownCount:false};if(!previous||previous.generation!==event.generation)return{baseline:next,terminal:attention,completedDelta:0,failedDelta:0,reset:false,generationChanged:previous!==null,unknownCount:attention!==null};const completed=event.counts.completed-previous.completed,failed=event.counts.failed-previous.failed,cancelled=(event.counts.cancelled??0)-previous.cancelled;if(completed<0||failed<0||cancelled<0)return{baseline:next,terminal:null,completedDelta:0,failedDelta:0,reset:true,generationChanged:false,unknownCount:false};const terminal=attention==="error"&&failed>0?"error":attention==="success"&&completed>0?"success":null;return{baseline:next,terminal,completedDelta:terminal?completed:0,failedDelta:terminal?failed:0,reset:false,generationChanged:false,unknownCount:false};}
/** Policy is evaluated after static safe rendering and per-message deduplication. */
export function shouldNotifyAttention(policy:NotificationPolicy,enabled:boolean,attention:PresenceUpdate["attention"],origin:"local"|"external",merged=false):boolean {if(!enabled||policy==="disabled"||!attention||attention==="none")return false;if(policy==="errors")return attention==="error";if(policy==="all")return true;if(policy==="settled")return attention==="error"||(attention==="success"&&(origin==="local"||merged));return origin==="external"||attention==="error"||merged;}
