import type { PresenceUpdate } from "./events.js";
import { boundedPresenceText } from "./text.js";
export type HerdrState = "idle" | "working" | "blocked" | "unknown";
const LOCAL: Record<PresenceUpdate["state"],string>={idle:"Idle",waiting:"Waiting",running:"Working",success:"Done",error:"Needs attention",cancelled:"Cancelled"};
export function compositeState(events: readonly PresenceUpdate[], active: boolean, locallyBlocked=false): HerdrState { if(locallyBlocked || events.some(e=>e.state==="error" || e.attention==="error"))return "blocked"; if(active || events.some(e=>e.state==="running" || e.state==="waiting"))return "working"; return "idle"; }
/** A native blocked label is process-local input; normalize it before it reaches Herdr. */
export function safeMessage(state:HerdrState,max:number,blockedMessage?:string):string { return boundedPresenceText(state==="blocked" ? (blockedMessage || "Pi needs attention") : state==="working" ? "Pi is working" : state==="idle" ? "Pi is idle" : "Pi state unknown",{maxBytes:128,maxCodePoints:max}); }
export function metadata(events:readonly PresenceUpdate[], state:HerdrState,max:number){ const count=(k:keyof PresenceUpdate["counts"])=>events.reduce((n,e)=>n+(typeof e.counts[k]==="number"?e.counts[k] as number:0),0);const tokens=events.reduce((n,e)=>n+(e.usage?.tokens??0),0);const cost=events.reduce((n,e)=>n+(e.usage?.cost??0),0);const context=Math.max(0,...events.map(e=>e.usage?.contextPercent??0));const progress=events.find(e=>e.source.id==="pi-todo"&&e.progress)??events.find(e=>e.progress&&(e.state==="running"||e.state==="waiting")); const labels:Record<string,string>={idle:"Idle",working:"Working",blocked:"Needs attention",unknown:"Unknown"}; return {title:boundedPresenceText(`Pi · ${labels[state]}`,{maxBytes:128,maxCodePoints:max}),displayAgent:"Pi",labels,tokens:{active:String(count("active")),completed:String(count("completed")),failed:String(count("failed")),queued:String(count("queued")),cancelled:String(count("cancelled")),total:String(count("total")),progress:progress?`${Math.round(progress.progress!.value*100)}%`:null,tokens:tokens?String(Math.round(tokens)):null,cost:cost?cost.toFixed(2):null,context:context?`${Math.round(context)}%`:null}}; }
export function attentionText(event:PresenceUpdate,max:number):{title:string;body:string;error:boolean}|null { if(event.attention!=="error"&&event.attention!=="success"&&event.attention!=="info")return null; const error=event.attention==="error"; return {title:boundedPresenceText(error?"Pi needs attention":"Pi update",{maxBytes:128,maxCodePoints:max}),body:boundedPresenceText(error?"A Pi task needs attention":"Pi activity completed",{maxBytes:512,maxCodePoints:max}),error}; }
export function localStateText(state:PresenceUpdate["state"],max:number){return boundedPresenceText(LOCAL[state],{maxBytes:128,maxCodePoints:max});}
