import * as path from "node:path";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { PresenceClient, type SessionRef } from "./client.js";
import type { PresenceConfig } from "./config.js";
import { PI_PRESENCE_READY_EVENT, PI_PRESENCE_UPDATE_EVENT, parsePresenceReady, parsePresenceRemove, parsePresenceSessionId, parsePresenceUpdate, PresenceEventRegistry, type PresenceUpdate } from "./events.js";
import { readHerdrIdentity } from "./identity.js";
import { NotificationDeduper, PI_SUBAGENT_SOURCE_ID, observeSubagentTerminal, shouldNotify, shouldNotifyAttention, type NotificationSeverity, type SubagentTerminalBaseline } from "./notification-policy.js";
import { officialHookStatus } from "./official-hook.js";
import { attentionText, blockedPresentationCategory, compositeState, isInteractionWaiting, isLiveInputRequest, metadata, safeMessage, type BlockedCategory } from "./presentation.js";
import { parseSubagentSummary, SubagentSummaryFence, type SubagentSummary } from "./subagent-summary.js";
import { HerdrSocketTransport } from "./transport.js";
import { TodoProgressAdapter } from "./todo.js";
import { UsageTracker } from "./usage.js";
import { hasControlOrBidi } from "./validation.js";
const LOCAL={id:"pi",label:"Pi",kind:"agent"}; const TODO="pi-todo"; const MAX_BLOCKED_COUNT=1_000_000; const MAX_BLOCKED_TRANSITIONS=Number.MAX_SAFE_INTEGER; const MAX_SUMMARY_TERMINALS=64;
type ContextUsageProvider={getContextUsage?:()=>unknown;sessionManager?:{getSessionId?:()=>unknown;getSessionFile?:()=>unknown}};
type Terminal="success"|"error"|"cancelled";
type RuntimeSession={id:string;ref:SessionRef};
function session(context:unknown):RuntimeSession|null { try { const manager=(context as ContextUsageProvider | undefined)?.sessionManager; const id=parsePresenceSessionId(manager?.getSessionId?.()); if(!id)return null; const file=manager?.getSessionFile?.(); if(typeof file==="string"&&file.length>0&&Buffer.byteLength(file,"utf8")<=1024&&!hasControlOrBidi(file)&&path.isAbsolute(file))return {id,ref:{agent_session_path:file}}; if(Buffer.byteLength(id,"utf8")>128)return null; return {id,ref:{agent_session_id:id}}; } catch{return null;} }
/** The last terminal message wins: an automatic retry can legitimately recover an earlier failure. */
export function deriveTerminalState(event:unknown, toolFailed=false):Terminal { const messages=(event as {messages?:unknown})?.messages; if(!Array.isArray(messages))return toolFailed?"error":"success"; for(let i=messages.length-1;i>=0;i--){const reason=(messages[i] as {stopReason?:unknown})?.stopReason;if(reason==="aborted"||reason==="cancelled")return "cancelled";if(reason==="error")return "error";if(typeof reason==="string")return "success";}return toolFailed?"error":"success"; }
/** Session-epoch-fenced composite renderer. It consumes generic retained sources without importing producers. */
export class PresenceRuntime {
 private registry=new PresenceEventRegistry(); private todo=new TodoProgressAdapter(); private client:PresenceClient|null=null; private sessionId:string|null=null; private sessionRef:SessionRef|null=null; private context:ContextUsageProvider|null=null; private epoch=0; private transitions:Promise<void>=Promise.resolve(); private generation=0; private sequence=0; private active=false; private rootSession=false; private blockedCount=0; private blockedTransitions=0; private nativeAskUserBlocked=false; private nativeGeneralBlocked=false; private inputLifecycleActive=false; private inputNotificationPending=false; private inputNotificationDelivered=false; private inputNotificationTransitions=0; private turn=0; private completed=0; private failed=0; private toolFailed=false; private terminal:Terminal="success"; private usage=new UsageTracker(); private ownReadyAdvertisement:object|null=null; private ownReadyRequest:object|null=null; private readyResponseInFlight=false; private clearTimer:ReturnType<typeof setTimeout>|undefined; private longRunningTimer:ReturnType<typeof setTimeout>|undefined; private subagentBaseline:SubagentTerminalBaseline|null=null; private subagentPending:{generation:number;sequence:number;attention:"success"|"error";completed:number;failed:number;deadline:number;timer:ReturnType<typeof setTimeout>}|null=null; private subagentSummary:SubagentSummary|null=null; private summaryFence=new SubagentSummaryFence(); private summaryTerminalExpiry=new Map<string,number>(); private summaryTerminalTimer:ReturnType<typeof setTimeout>|undefined; private notifications=new NotificationDeduper();
 constructor(private pi:ExtensionAPI,private config:PresenceConfig){}
 async startSession(context:unknown,event?:unknown){const epoch=++this.epoch;return this.transition(()=>this.beginSession(context,event,epoch));}
 private transition(work:()=>Promise<void>):Promise<void>{const next=this.transitions.then(work,work);this.transitions=next.catch(()=>{});return next;}
 private async beginSession(context:unknown,event:unknown,epoch:number){
  await this.teardown(); if(epoch!==this.epoch)return;
  if((context as {mode?:unknown})?.mode!=="tui")return;
  const identity=readHerdrIdentity(); const current=session(context); if(!identity||!current)return;
  let managed=true;try{managed=(await officialHookStatus())!=="absent";}catch{managed=true;}
  if(epoch!==this.epoch||managed)return;
  const client=new PresenceClient(identity,new HerdrSocketTransport(identity.socketPath,this.config.timeoutMs,this.config.maxQueue),this.config);
  this.client=client;this.sessionId=current.id;this.sessionRef=current.ref;this.context=context as ContextUsageProvider;this.generation++;this.sequence=0;this.registry.start(current.id);this.rootSession=true;this.active=false;this.blockedCount=0;this.blockedTransitions=0;this.nativeAskUserBlocked=false;this.nativeGeneralBlocked=false;this.inputLifecycleActive=false;this.inputNotificationPending=false;this.inputNotificationDelivered=false;this.inputNotificationTransitions=0;this.turn=0;this.completed=0;this.failed=0;this.toolFailed=false;this.terminal="success";this.usage=new UsageTracker();
  await client.reportSession(current.ref,typeof (event as {reason?:unknown})?.reason==="string"?(event as {reason:string}).reason:undefined);
  if(epoch!==this.epoch||this.client!==client)return;
  this.ready(current.id);this.updateContextUsage();let reloadActive=false;try{reloadActive=(context as {isIdle?:()=>boolean}).isIdle?.()===false;}catch{}if(reloadActive){this.active=true;this.turn++;this.startLongRunningTimer();this.publish("running");}else this.publish("idle");
 }
 handlePresenceUpdate(payload:unknown){try{const e=parsePresenceUpdate(payload);if(!e||e.source.id===LOCAL.id||e.source.id===TODO||!this.registry.acceptParsed(e))return;if(e.source.id===PI_SUBAGENT_SOURCE_ID){this.summaryFence.recordUpdate(e);if(this.subagentSummary&&(this.subagentSummary.generation!==e.generation||this.subagentSummary.sequence!==e.sequence))this.clearSubagentSummary();this.queueSubagent(e);}else this.render(e);this.syncInputNotification();}catch{}}
 handlePresenceRemove(payload:unknown){try{const e=parsePresenceRemove(payload);if(!e||e.source.id===LOCAL.id||e.source.id===TODO)return;const accepted=this.registry.acceptParsedRemove(e).accepted;if(!accepted)return;if(e.source.id===PI_SUBAGENT_SOURCE_ID){this.summaryFence.recordRemove(e);if(this.subagentPending)clearTimeout(this.subagentPending.timer);this.subagentPending=null;this.subagentBaseline=null;this.clearSubagentSummary();this.clearSummaryTerminalExpiry();}this.render();this.syncInputNotification();}catch{}}
 /** Strict companion summary hook; ids/tasks/output are never rendered or sent to Herdr. */
 handleSubagentSummary(payload:unknown){try{const next=parseSubagentSummary(payload);if(!next||next.sessionId!==this.sessionId||next.source.id!==PI_SUBAGENT_SOURCE_ID||!this.summaryFence.acceptSummary(next))return;this.subagentSummary=this.retainSummaryTerminal(next);this.render();}catch{}}
 /** Native same-process guardrail event: only the current root TUI session may affect it. */
 handleBlocked(payload:unknown){try{if(!this.rootSession||!payload||typeof payload!=="object")return;const data=payload as {active?:unknown;label?:unknown};if(typeof data.active!=="boolean")return;const wasBlocked=this.blockedCount>0;const wasGeneralBlocked=this.nativeGeneralBlocked;const askUser=data.label==="ask-user";if(data.active){this.blockedCount=Math.min(MAX_BLOCKED_COUNT,this.blockedCount+1);if(askUser)this.nativeAskUserBlocked=true;else this.nativeGeneralBlocked=true;}else{this.blockedCount=Math.max(0,this.blockedCount-1);if(this.blockedCount===0){this.nativeAskUserBlocked=false;this.nativeGeneralBlocked=false;}}const isBlocked=this.blockedCount>0;if(wasBlocked!==isBlocked)this.blockedTransitions=Math.min(MAX_BLOCKED_TRANSITIONS,this.blockedTransitions+1);this.render();this.syncInputNotification();if(data.active&&!askUser&&!wasGeneralBlocked)this.notify("attention",`blocked:${this.turn}:${this.blockedTransitions}`,"Pi needs attention","Pi needs attention","local");}catch{}}
 handleReady(payload:unknown){try{if(payload===this.ownReadyAdvertisement||payload===this.ownReadyRequest||this.readyResponseInFlight)return;const r=parsePresenceReady(payload);if(!r||r.sessionId!==this.sessionId||r.consumer)return;this.readyResponseInFlight=true;try{this.advertise(r.sessionId);for(const e of this.registry.snapshot().filter(x=>x.source.id===LOCAL.id||x.source.id===TODO))this.emit({...e,generation:this.generation,sequence:++this.sequence,attention:"none"});}finally{this.readyResponseInFlight=false;}}catch{}}
 handleAgentStart(context?:unknown){if(!this.rootSession||!this.sessionId)return;const refreshed=session(context);if(refreshed&&refreshed.id===this.sessionId)this.sessionRef=refreshed.ref;const client=this.client;const ref=this.sessionRef;const epoch=this.epoch;if(client&&ref)void client.reportSession(ref).then(()=>{if(epoch!==this.epoch||this.client!==client)return;}).catch(()=>{});this.clear();if(!this.active){this.active=true;this.turn++;this.terminal="success";this.toolFailed=false;this.usage=new UsageTracker();this.startLongRunningTimer();}this.updateContextUsage();this.publish("running");}
 handleTurnStart(context:unknown){if(context&&typeof context==="object")this.context=context as ContextUsageProvider;this.updateContextUsage();}
 handleAgentEnd(event:unknown){if(this.rootSession)this.terminal=deriveTerminalState(event,this.toolFailed);}
 handleAgentSettled(context:unknown){try{const idle=(context as {isIdle?:()=>boolean})?.isIdle;if(idle&&idle()===false)return;}catch{return;}if(!this.rootSession||!this.sessionId||!this.active)return;this.active=false;this.clearLongRunningTimer();this.updateContextUsage();if(this.terminal==="error")this.failed++;else if(this.terminal==="success")this.completed++;this.publish(this.terminal,this.terminal==="cancelled"?"none":this.terminal);const now=this.epoch;this.clearTimer=setTimeout(()=>{if(this.epoch===now&&!this.active)this.render();},this.config.finalClearMs);this.clearTimer.unref?.();}
 handleAgentEndFallback(){this.handleAgentSettled({});}
 handleMessageEnd(event:unknown){const m=(event as {message?:{role?:unknown;usage?:unknown}})?.message;if(m?.role==="assistant"){this.usage.add(m.usage);this.updateContextUsage();}}
 handleToolResult(event:unknown){if((event as {isError?:unknown})?.isError===true&&this.active)this.toolFailed=true;if(!this.rootSession||!this.sessionId)return;let todo:PresenceUpdate|null=null;try{todo=this.todo.accept(event,this.pi.getAllTools(),this.sessionId,this.generation,++this.sequence)}catch{}if(todo&&this.registry.acceptParsed(todo)){this.render(todo);this.syncInputNotification();this.emit(todo);}}
 async shutdownSession(){++this.epoch;return this.transition(()=>this.teardown());}
 private publish(state:PresenceUpdate["state"],attention:PresenceUpdate["attention"]="none"){if(!this.rootSession||!this.sessionId)return;const e:PresenceUpdate={version:1,sessionId:this.sessionId,generation:this.generation,sequence:++this.sequence,source:{...LOCAL},state,counts:{active:this.active?1:0,completed:this.completed,failed:this.failed},...(this.usage.snapshot()?{usage:this.usage.snapshot()}:{}),attention};if(this.registry.acceptParsed(e)){this.render(e);this.syncInputNotification();this.emit(e);}}
 private nativeBlockedCategory():BlockedCategory|undefined{return this.nativeGeneralBlocked?"blocked":this.nativeAskUserBlocked?"ask-user":undefined;}
 private effectiveBlockedCategory(events:readonly PresenceUpdate[]):BlockedCategory{return blockedPresentationCategory(events,this.nativeBlockedCategory());}
 /** One retained input lifecycle yields at most one alert; suppressed live intent remains pending. */
 private syncInputNotification(){const events=this.registry.snapshot();const inputPresent=this.nativeAskUserBlocked||events.some(isInteractionWaiting);if(!inputPresent){this.inputLifecycleActive=false;this.inputNotificationPending=false;this.inputNotificationDelivered=false;return;}if(!this.inputLifecycleActive)this.inputLifecycleActive=true;if(this.inputNotificationDelivered)return;if(this.nativeAskUserBlocked||events.some(isLiveInputRequest))this.inputNotificationPending=true;const effective=!this.nativeGeneralBlocked&&!events.some(e=>e.state==="error"||e.attention==="error");if(!effective||!this.inputNotificationPending)return;this.inputNotificationTransitions=Math.min(MAX_BLOCKED_TRANSITIONS,this.inputNotificationTransitions+1);this.inputNotificationDelivered=this.notify("attention",`input:${this.turn}:${this.inputNotificationTransitions}`,"Pi needs your input","Pi needs your input","local");if(this.inputNotificationDelivered)this.inputNotificationPending=false;}
 private render(attention?:PresenceUpdate){const ref=this.sessionRef;const client=this.client;if(!this.rootSession||!ref||!client)return;const events=this.registry.snapshot();const state=compositeState(events,this.active,this.blockedCount>0);const category=this.effectiveBlockedCategory(events);void client.report(state,ref,safeMessage(state,this.config.maxLabelChars,category,events));void client.metadata(metadata(events,state,this.config.maxLabelChars,this.subagentSummary,category));const text=attention&&attentionText(attention,this.config.maxLabelChars);if(text&&!text.inputNeeded&&shouldNotifyAttention(this.config.notificationPolicy,this.config.notifications,attention.attention,attention.source.id===LOCAL.id?"local":"external")){const key=`${attention.source.id}:${attention.generation}:${attention.sequence}:${this.turn}:${attention.attention}`;this.notify(attention.attention==="error"?"error":attention.attention==="success"?"success":"info",key,text.title,text.body,attention.source.id===LOCAL.id?"local":"external");}}
 private queueSubagent(event:PresenceUpdate){const observed=observeSubagentTerminal(this.subagentBaseline,event);this.subagentBaseline=observed.baseline;if(observed.reset||observed.generationChanged){if(this.subagentPending)clearTimeout(this.subagentPending.timer);this.subagentPending=null;}if(observed.generationChanged)this.clearSummaryTerminalExpiry();this.render();if(!observed.terminal)return;const prior=this.subagentPending;if(prior&&prior.generation===event.generation){prior.attention=observed.terminal==="error"?"error":prior.attention;prior.completed+=observed.completedDelta;prior.failed+=observed.failedDelta;prior.sequence=event.sequence;return;}if(prior)clearTimeout(prior.timer);const pending={generation:event.generation,sequence:event.sequence,attention:observed.terminal,completed:observed.completedDelta,failed:observed.failedDelta,deadline:Date.now()+(observed.terminal==="error"?100:450),timer:undefined as unknown as ReturnType<typeof setTimeout>};pending.timer=this.scheduleSubagent(pending);this.subagentPending=pending;}
 private scheduleSubagent(pending:{generation:number;sequence:number;attention:"success"|"error";completed:number;failed:number;deadline:number;timer:ReturnType<typeof setTimeout>}){const epoch=this.epoch;const timer=setTimeout(()=>{if(this.epoch!==epoch||this.subagentPending!==pending)return;this.subagentPending=null;const event:PresenceUpdate={version:1,sessionId:this.sessionId??"",generation:pending.generation,sequence:pending.sequence,source:{id:PI_SUBAGENT_SOURCE_ID,label:"Subagents",kind:"aggregate"},state:pending.attention==="error"?"error":"success",counts:{active:0,completed:pending.completed,failed:pending.failed},attention:pending.attention};this.render(event);},Math.max(0,pending.deadline-Date.now()));timer.unref?.();return timer;}
 private notify(severity:NotificationSeverity,key:string,title:string,body:string,origin:"local"|"external"):boolean{if(!shouldNotify(this.config.notificationPolicy,this.config.notifications,severity,origin)||!this.notifications.accept(key))return false;void this.client?.notify(title,body,severity==="error"||severity==="attention");return true;}
 private summaryTerminalIdentity(summary:SubagentSummary):string|undefined{const terminal=summary.terminal;return terminal?`${terminal.id}\u0000${terminal.status}\u0000${terminal.completedAt}`:undefined;}
 private retainSummaryTerminal(summary:SubagentSummary):SubagentSummary{if(this.summaryTerminalTimer)clearTimeout(this.summaryTerminalTimer);this.summaryTerminalTimer=undefined;const identity=this.summaryTerminalIdentity(summary);if(!identity)return summary;const now=Date.now();let deadline=this.summaryTerminalExpiry.get(identity);if(deadline===undefined){deadline=now+this.config.finalClearMs;}else{this.summaryTerminalExpiry.delete(identity);}this.summaryTerminalExpiry.set(identity,deadline);while(this.summaryTerminalExpiry.size>MAX_SUMMARY_TERMINALS)this.summaryTerminalExpiry.delete(this.summaryTerminalExpiry.keys().next().value!);if(deadline<=now)return {...summary,terminal:undefined};this.summaryTerminalTimer=setTimeout(()=>{if(this.summaryTerminalIdentity(this.subagentSummary??summary)!==identity)return;this.subagentSummary={...(this.subagentSummary??summary),terminal:undefined};this.render();},deadline-now);this.summaryTerminalTimer.unref?.();return summary;}
 private clearSubagentSummary(){if(this.summaryTerminalTimer)clearTimeout(this.summaryTerminalTimer);this.summaryTerminalTimer=undefined;this.subagentSummary=null;}
 private clearSummaryTerminalExpiry(){this.summaryTerminalExpiry.clear();}
 private startLongRunningTimer(){this.clearLongRunningTimer();const epoch=this.epoch;const turn=this.turn;this.longRunningTimer=setTimeout(()=>{this.longRunningTimer=undefined;if(this.epoch===epoch&&this.active&&this.turn===turn)this.notify("long-running",`long-running:${turn}`,"Pi is still working","A Pi task is taking longer than expected","local");},this.config.longRunningMs);this.longRunningTimer.unref?.();}
 private clearLongRunningTimer(){if(this.longRunningTimer)clearTimeout(this.longRunningTimer);this.longRunningTimer=undefined;}
 private ready(id:string){this.advertise(id);const request=Object.freeze({version:1 as const,sessionId:id});try{this.ownReadyRequest=request;this.pi.events.emit(PI_PRESENCE_READY_EVENT,request);}catch{}finally{this.ownReadyRequest=null;}}
 private advertise(id:string){const ad=Object.freeze({version:1 as const,sessionId:id,consumer:Object.freeze({id:"pi-herdr-presence",capabilities:Object.freeze(["presence-remove-v1","presence-summary-v1","herdr-pane-report-agent-v1","herdr-pane-report-metadata-v1"])})});try{this.ownReadyAdvertisement=ad;this.pi.events.emit(PI_PRESENCE_READY_EVENT,ad);}catch{}finally{this.ownReadyAdvertisement=null;}}
 private emit(e:PresenceUpdate){try{this.pi.events.emit(PI_PRESENCE_UPDATE_EVENT,e)}catch{}}
 private updateContextUsage(){try{this.usage.setContext(this.context?.getContextUsage?.());}catch{}}
 private clear(){if(this.clearTimer)clearTimeout(this.clearTimer);this.clearTimer=undefined;}
 private async teardown(){this.clear();this.clearLongRunningTimer();if(this.subagentPending)clearTimeout(this.subagentPending.timer);this.subagentPending=null;this.subagentBaseline=null;this.clearSubagentSummary();this.summaryFence.reset();this.clearSummaryTerminalExpiry();this.notifications.clear();this.readyResponseInFlight=false;this.ownReadyAdvertisement=null;this.ownReadyRequest=null;this.registry.stop();this.sessionId=null;this.sessionRef=null;this.context=null;this.active=false;this.rootSession=false;this.blockedCount=0;this.blockedTransitions=0;this.nativeAskUserBlocked=false;this.nativeGeneralBlocked=false;this.inputLifecycleActive=false;this.inputNotificationPending=false;this.inputNotificationDelivered=false;this.inputNotificationTransitions=0;const client=this.client;this.client=null;if(!client)return;await client.teardown(this.config.timeoutMs).catch(()=>{});}
}
